on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
        
    steps:
      - name: Access External URL with curl
        run: |
          curl -L -v https://www.93fm.co.il/radio/broadcast/