on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
          
      - name: Build
        run: pyinstaller --onefile --name getwave main.py

      - name: Download
        run: dist/getwave.exe --station 1 --program 222 --broadcasts "2-5,8" --yes --output "./dist" -pr 3 --index 5 
