name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
          
      - name: Build
        run: pyinstaller --onefile --name getwave main.py

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: dist/getwave.exe
